### ISSUE TITLE
2.6.0 and 2.6.1 throw Error Undefined constant "OCA\Gestion\Migration\notnull"

### ISSUE THREAD

**Issue by nursoda** [baimard/gestion#411]
On latest NC30 I get this when doing an app update via occ. Similarly got it yesterday for 2.6.0:

```
gestion new version available: 2.6.1
An unhandled exception has been thrown:
Error: Undefined constant "OCA\Gestion\Migration\notnull" in /PATH/apps/gestion/lib/Migration/Version20300Date20230714134445.php:116
Stack trace:
#0 /PATH/lib/private/DB/MigrationService.php(504): OCA\Gestion\Migration\Version20300Date20230714134445->changeSchema()
#1 /PATH/lib/private/DB/MigrationService.php(395): OC\DB\MigrationService->executeStep()
#2 /PATH/lib/private/legacy/OC_App.php(736): OC\DB\MigrationService->migrate()
#3 /PATH/lib/private/Installer.php(151): OC_App::updateApp()
#4 /PATH/core/Command/App/Update.php(87): OC\Installer->updateAppstoreApp()
#5 /PATH/3rdparty/symfony/console/Command/Command.php(298): OC\Core\Command\App\Update->execute()
#6 /PATH/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#7 /PATH/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#8 /PATH/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#9 /PATH/lib/private/Console/Application.php(183): Symfony\Component\Console\Application->run()
#10 /PATH/console.php(87): OC\Console\Application->run()
#11 /PATH/occ(11): require_once('...')
#12 {main}upgrade
```

**Comment by baimard** [comment]
Oupsi, sorry just a little mistake. Is it OK with 2.6.2 ?

tell me.

**Comment by nursoda** [comment]
Yes, 2.6.2 is fine. Thanks!
